version: '3.9'

services:
  app:
    build: .
    ports:
      - '8080'
    environment:
      - PORT=${PORT:-8080}
      - NODE_ENV=production
      - APP_NAME=${APP_NAME}
      - HOSTS=${HOSTS}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.${APP_NAME}.rule=${HOSTS}"
      - 'traefik.http.routers.${APP_NAME}.entrypoints=websecure'

        # Apply the redirect middleware to this router
      - 'traefik.http.routers.${APP_NAME}.middlewares=redirect-www-to-non-www@docker'

      - 'traefik.http.services.${APP_NAME}.loadbalancer.server.port=${PORT:-8080}'
      - 'traefik.http.routers.${APP_NAME}.tls=true'
      - 'traefik.http.routers.${APP_NAME}.tls.certresolver=letsencrypt'

      # Define the Middleware using redirectregex (same service, different label group)
      - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.regex=^https?://www\\.(.*)"
      - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.permanent=true"
networks:
  traefik-net:
    external: true
