import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/component/footer";

export const metadata: Metadata = {
  title: "InfraFund",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
      <Footer/>
    </html>
  );
}
