import type { Metadata } from 'next';
import './globals.css';
import Footer from '@/component/footer';
import PathnameWrapper from './PathnameWrapper';
import Script from 'next/script';
export const metadata: Metadata = {
  title: 'InfraFund',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Script
          src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}`}
          strategy="afterInteractive"
        />
        <PathnameWrapper>{children}</PathnameWrapper>
        <Footer />
      </body>
    </html>
  );
}
