import Footer from '@/component/footer';
import { Providers } from '@/providers/Providers';
import type { Metadata } from 'next';
import './globals.css';
import PathnameWrapper from './PathnameWrapper';

export const metadata: Metadata = {
  title: 'InfraFund',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <PathnameWrapper>{children}</PathnameWrapper>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
