name: Run some checks & build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run format checks
        run: npm run format
        continue-on-error: false

      - name: Run Knip checks
        run: npm run format:knip
        continue-on-error: false

      - name: Build Next.js app
        run: npm run build
        env:
          NODE_ENV: production
        continue-on-error: false
