name: Deploy to Dev Environment
on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: Build docker image
    runs-on: develop-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build Docker image
        run: docker build --no-cache -f ./deployment/Dockerfile -t infra-landing:dev .

  deploy:
    name: Deploy to Development Server
    runs-on: develop-runner
    needs: build
    steps:
      - name: Deploy with Docker Compose
        run: docker compose -f ${{ vars.DOCKER_COMPOSE_PATH_DEVELOP }} up -d landing --force-recreate
      - name: Check status
        run: docker compose -f ${{ vars.DOCKER_COMPOSE_PATH_DEVELOP }} ps