name: Deploy to Dev Environment
on:
  push:
    branches: ['develop']

jobs:
  build:
    name: Build docker image
    runs-on: [self-hosted, infrafund-develop]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build Docker image
        env:
          BUILD_ARG_API: ${{ secrets.DEV_API_BASE_URL }}
          BUILD_ARG_DASH_LOGIN: ${{ secrets.DEV_DASHBOARD_URL }}
          BUILD_ARG_RECAPTCHA: ${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}
          BUILD_ARG_PARTICLE_PROJECT: ${{ secrets.DEV_PARTICLE_PROJECT_ID }}
          BUILD_ARG_PARTICLE_CLIENT: ${{ secrets.DEV_PARTICLE_CLIENT_KEY }}
          BUILD_ARG_PARTICLE_APP: ${{ secrets.DEV_PARTICLE_APP_ID }}
        run: |
          docker build \
            -f ./deployment/Dockerfile \
            --build-arg NEXT_PUBLIC_API_BASE_URL="$BUILD_ARG_API" \
            --build-arg NEXT_PUBLIC_DASH_LOGIN_URL="$BUILD_ARG_DASH_LOGIN" \
            --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_KEY="$BUILD_ARG_RECAPTCHA" \
            --build-arg NEXT_PUBLIC_PROJECT_ID="$BUILD_ARG_PARTICLE_PROJECT" \
            --build-arg NEXT_PUBLIC_CLIENT_KEY="$BUILD_ARG_PARTICLE_CLIENT" \
            --build-arg NEXT_PUBLIC_APP_ID="$BUILD_ARG_PARTICLE_APP" \
            -t infra-landing:dev .

  deploy:
    name: Deploy to Development Server
    runs-on: [self-hosted, infrafund-develop]
    needs: build
    steps:
      - name: Deploy with Docker Compose
        run: docker compose -f ${{ vars.DOCKER_COMPOSE_PATH_DEVELOP }} up -d landing --force-recreate
      - name: Wait for container readiness
        run: |
          echo "Waiting for container to be ready..."
          sleep 5
          docker compose -f ${{ vars.DOCKER_COMPOSE_PATH_DEVELOP }} ps

      - name: Verify deployment
        run: |
          docker compose -f ${{ vars.DOCKER_COMPOSE_PATH_DEVELOP }} logs --tail=20 landing
